#!/usr/bin/env python3
from pathlib import Path
import csv,json,html
DOC=Path(__file__).resolve().parents[1]
nets={
 'PV_POS':['PV1.+','U0.IN+'], 'PV_RETURN':['PV1.-','U0.IN-'],
 'CHARGE_5V':['U0.OUT+','M1.IN+'],'CHARGE_RETURN':['U0.OUT-','M1.IN-'],
 'CELL1_POS':['BT1.+','FB1.1'],'CELL2_POS':['BT2.+','FB2.1'],
 'PACK_POS':['FB1.2','FB2.2','M1.B+'],'PACK_NEG':['BT1.-','BT2.-','M1.B-'],
 'PROTECTED_POS':['M1.OUT+','F2.1'],'FUSED_POS':['F2.2','S1.1'],
 'VBAT_SYS':['S1.2','M2.VCC','C3.+','C4.1','U3.VIN','C2.+','R5.1'],
 'GND_LOAD':['M1.OUT-','M2.GND','C3.-','C4.2','JLED.-','R4.2','SW1.2','U3.GND','C2.-','M3.G','Q2.E','R9.2'],
 'PWM':['M2.D9','R3.1'],'LED_POS':['R3.2','JLED.+'],
 'LDR_POWER':['M2.D7','LDR1.1'],'LDR_SENSE':['LDR1.2','R4.1','M2.A1'],
 'TEST':['M2.D2','SW1.1'],'UART_TX':['M2.D1/TX','R8.1'],
 'UART_BASE':['R8.2','R9.1','Q2.B'],'UART_RX_INVERTED':['Q2.C','R10.2','M3.D6'],
 'ESP_3V3':['U3.VOUT','M3.3V3','R10.1'],'ADC_BATT':['R5.2','M3.A0'],'WAKE':['M3.D0','M3.RST']}
(DOC/'reviewed-netlist.json').write_text(json.dumps({'revision':'v0.5 live project configuration','scope':'External module terminals only; internal connections must be verified. Not a PCB netlist.','nets':nets},indent=2)+'\n')
with (DOC/'wire-schedule.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['Net','Connect these terminals together','Notes'])
 for n,p in nets.items():w.writerow([n,'; '.join(p),'NO bridge to OUT-/GND_LOAD' if n=='PACK_NEG' else ''])
# Catch accidental reuse and protection-domain merges in the external wiring model.
seen={}
for n,pins in nets.items():
 for p in pins:
  assert p not in seen,(p,n,seen.get(p));seen[p]=n
assert seen['M1.B-']!=seen['M1.OUT-']
assert seen['M1.IN-']!=seen['M1.OUT-'] # no external link, internal board may join
assert seen['M3.3V3']!=seen['M2.VCC']
assert seen['JLED.-']==seen['M1.OUT-']   # string return goes to load ground, no switch
assert 'Q1.G' not in seen and 'R6.1' not in seen and 'F1.1' not in seen  # driver parts removed 20-Sep-2026
assert seen['R3.1']==seen['M2.D9']       # R3 is fed from the pin, not the battery rail
assert seen['M3.D6']==seen['Q2.C']
assert 'M3.D5' not in seen and 'M2.D8' not in seen and 'M2.A0' not in seen
(DOC.parent/'validation/reviewed-wiring-check.txt').write_text(f'PASS: {len(nets)} external nets, {len(seen)} unique terminals; battery negative separate; no external IN-/OUT- link; ESP supply separate; direct pin drive of the LED branch and inverted development UART checked.\nThis verifies the authored wiring schedule, not module internals or physical construction.\n')
rows=''.join('<tr><td><code>'+html.escape(n)+'</code></td><td>'+html.escape(' / '.join(p))+'</td></tr>' for n,p in nets.items())
drawings=[
 ('01-power','01 / Power and charging','Reuse the existing panel and protected charger. U0 is an open item: the bench uses a 5 V panel straight into the charger until the production panel is chosen. Each cell has its own positive-terminal fuse.','sheet-1.png'),
 ('02-controller','02 / Controller and LED circuit','The BTE13-010A has been converted to its internal 8 MHz clock. Feed the protected battery rail into VCC, leave RAW open, and keep the LDR on the protected load side.','sheet-2.png'),
 ('03-telemetry','03 / Low-power telemetry reference (D1 Mini)','This retained D1 Mini wiring is the later low-power production reference. It is not the always-on D1 Mini UART test system.','sheet-3.png'),
 ('06-telemetry-dev','06 / Development telemetry (Wemos D1 Mini)','Test system only: the always-on D1 captures Arduino diagnostics through the existing transistor interface and sends them to Home Assistant without an Arduino USB connection.','sheet-6.png'),
 ('04-assembly','04 / Physical assembly','An enclosure placement concept with socketed modules, accessible terminals, protected rails and separation between heat-producing parts and cells. This is not a dimensional template.','sheet-4.png'),
 ('07-current-architecture','07 / Current architecture schematic','Live v0.5 wiring, including the D1/TX-to-D6 development UART. <a href="../kicad_current/SolarLights_Lite_Current.kicad_sch">Open the editable KiCad schematic</a>.','sheet-7.png'),
]
svgs=[]
for name,_,_,_ in drawings:
 s=(DOC/(name+'.svg')).read_text();s=s[s.index('<svg'):];svgs.append(s)
staging_svg=(DOC/'05-staging.svg').read_text();staging_svg=staging_svg[staging_svg.index('<svg'):]
sections=[]
for i,((name,title,desc,png),svg) in enumerate(zip(drawings,svgs),1):
 sections.append(f'<section id="s{i}"><h2>{title}</h2><p>{desc}</p><div class="drawing">{svg}</div><p class="small"><a href="{name}.svg">Open full-size SVG</a> · <a href="{png}">PNG preview</a></p></section>')
staging='''<section id="staging"><h2>05 / Staged testing and serial diagnostics</h2>
<p class="lede"><b>Stop and test after every stage.</b> Do not assemble the complete battery, charger, solar input and controller and then apply power for the first time. Each row below is an acceptance gate: proceed only after the measured result passes.</p>
<div class="danger"><b>Never connect two positive power sources to the Pro Mini.</b> In v0.5, use the D1 Mini's protected, receive-only Q2/R8/R9/R10 path for diagnostics. A temporary USB-UART monitor is optional: its VCC/3V3/5V lead remains open, with only adapter RX and OUT- connected.</div>
<div class="drawing">'''+staging_svg+'''</div>
<p class="small"><a href="05-staging.svg">Open full-size SVG</a> · <a href="sheet-5.png">PNG preview</a> · the D1 Mini test receiver replaces the normal Arduino USB-UART cable</p>
<p class="small">Use <b>OUT- / GND_LOAD</b> for the D1 Mini receiver ground, never B-. Arduino D1/TX enters the existing R8/Q2/R9/R10 interface and Q2's collector reaches D1 Mini D6. The temporary USB adapter arrangement remains available only when physically needed.</p>
<div class="scroll"><table class="stages"><thead><tr><th>Stage</th><th>Connect or change</th><th>Test and expected result</th><th>Pass before continuing</th></tr></thead><tbody>
<tr><td><b>0<br>Power off</b></td><td>Identify M1 pads by their printed labels: IN+/IN-, B+/B-, OUT+/OUT-. Confirm M2's onboard regulator is removed or isolated. Leave RAW open. Set the main switch open.</td><td>Use continuity and polarity checks only. Confirm the external wiring does not bridge M1 B- to OUT-. Inspect battery sleeves, holders, fuses and polarity.</td><td>No shorts from VBAT_SYS to GND_LOAD. Every connector is labelled. Battery and panel remain disconnected.</td></tr>
<tr><td><b>1<br>Controller</b></td><td>Use a current-limited 3.8 V bench supply directly across M2 VCC/GND. No cell, charger or panel. Connect LEDs, D2 and the v0.5 receive-only D1 Mini monitor.</td><td>Compare Home Assistant <code>Arduino VDD</code> with a meter at VCC/GND. On reset expect the startup test; D2-to-GND should produce <code>output=100%</code>. Check D9 and LED current.</td><td>Reported voltage is within about 0.05 V after calibration. No hot parts. With R3=47 ohm, LED current is near the documented value for the applied voltage.</td></tr>
<tr><td><b>2<br>Protected battery</b></td><td>Power down. Connect one suitable 1S cell to M1 B+/B-. Connect M1 OUT+ through F2 and S1 to M2 VCC; connect M1 OUT- to M2 GND. Bench: power the D1 Mini from its micro-USB with U3 OUT disconnected from its 3V3 pin. Production: U3 (TPS63802, 3.3 V, VIN on VBAT_SYS) is its only supply. Never connect both.</td><td>With S1 open, measure correct polarity and cell-like voltage at OUT+/OUT-. Close S1 and watch the Home Assistant diagnostic line. Compare <code>Arduino VDD</code> with the meter again and repeat the D2 test.</td><td>The controller is powered only from OUT+/OUT-. Diagnostics remain fresh through D1/TX, Q2 and D6 with common OUT- ground. No abnormal heating or unexplained current.</td></tr>
<tr><td><b>3<br>LDR and timing</b></td><td>Fit D7 -&gt; LDR -&gt; A1 -&gt; 47k -&gt; OUT-. Keep the sensor shaded from the LEDs.</td><td>In stable daylight/off operation, timestamps advance by about 8 s. Covering the LDR changes them to about 1 s while darkness is confirmed. After 300 s, expect state 1 and a 2%/s brightness ramp. Uncover for 300 s to return to state 0.</td><td>Short shadows or light flashes do not cause a transition. The threshold gap prevents flicker. Below 3.45 V, normal night duty settles at 50%.</td></tr>
<tr><td><b>4<br>Low voltage</b></td><td>Return to the current-limited bench supply for this test; do not deliberately over-discharge a lithium cell. Establish night mode, then lower VCC.</td><td>Below 3.30 V for about 30 scheduler seconds, expect <code>state=4 pct=0</code> with immediate shutdown. D2 must not relight it. Recovery requires over 3.60 V and confirmed daylight.</td><td>Cutoff, button lockout and daylight recovery all pass with <code>TIME_SCALE=1</code>.</td></tr>
<tr><td><b>5<br>5 V charger input</b></td><td>Open item: U0 is not fitted on the bench, where a 5 V panel feeds M1 IN directly. For production, test the selected U0 (MP1584 candidate) separately from a current-limited source. With its output disconnected, adjust it to 5.00 V. Check startup, load regulation and reverse leakage before connecting U0 OUT to M1 IN.</td><td>Confirm 5.00 V at M1 IN+/IN-. Identify the charger PROG resistor and begin with a verified conservative 100-150 mA charge setting. Monitor actual charge current and temperature.</td><td>Correct input voltage, current limit, termination near 4.2 V and acceptable temperatures. A CHRG LED alone is not a pass.</td></tr>
<tr><td><b>6<br>Solar panel</b></td><td>Power down, then connect panel +/− to U0 IN+/IN-. Never connect the approximately 7.6 V open-circuit panel directly to M1 or M2.</td><td>Measure panel voltage, U0's regulated 5 V output, battery voltage and actual charging current in sun, shade and recovery from weak light. Check night-time reverse current.</td><td>U0 remains regulated without overheating, charging recovers after shade, and reverse leakage is acceptable or a qualified blocking solution is fitted.</td></tr>
<tr><td><b>7<br>Long run</b></td><td>Only after stages 0-6 pass, add the optional telemetry branch. Run at least 14 days before sealing the enclosure.</td><td>Log daily battery voltage, Arduino state, dusk/dawn behaviour, LVC events and D1 health. Measure charge/load current, energy and temperatures with suitable external instruments; they are not v0.5 telemetry entities. Test poor Wi-Fi and unavailable services separately.</td><td>No progressive energy deficit, reset loop, unsafe temperature or unexplained state transition. Disable serial diagnostics for the final low-power measurement.</td></tr>
</tbody></table></div>
<h3>How to read the diagnostic serial output</h3>
<div class="scroll"><table><thead><tr><th>Observed output</th><th>Meaning / expected validation</th></tr></thead><tbody>
<tr><td><code>mode=DAY output=0% cause=DAY_OFF</code><br><code>next_tick=8s</code></td><td>Stable daylight state, lights off and low-power watchdog interval. A stable heartbeat prints approximately once per 60 scheduler seconds.</td></tr>
<tr><td><code>ldr=12.4% raw=127 ldr_v=0.418V sense=DARK</code><br><code>confirm=DUSK 40/300s</code></td><td>A1 is below the 30% dark threshold and the five-minute dusk confirmation is in progress. Progress prints every 10 seconds without emitting one line per wake.</td></tr>
<tr><td><code>mode=DAY output=100% cause=BUTTON_TEST</code><br><code>button=59s</code></td><td>D2's manual test is active. DAY is correct: the button overrides output without changing the day/night mode.</td></tr>
<tr><td><code>mode=EVENING night=YES output=2%</code><br><code>cause=ALL_NIGHT</code></td><td>Five minutes of darkness were confirmed and the automatic dusk fade has begun. Fade progress reports at approximately 10-percentage-point changes.</td></tr>
<tr><td><code>battery=LOW output=50%</code><br><code>cause=LOW_BATT_NIGHT</code></td><td>Normal all-night operation while reported VCC is between 3.30 V and 3.45 V; automatic night output is halved.</td></tr>
<tr><td><code>mode=LVC output=0% cause=LVC_OFF</code></td><td>Low-voltage cutoff. Output must remain off even if D2 is pressed. <code>lvc=.../30s</code> shows the cutoff timer.</td></tr>
</tbody></table></div>
<div class="note"><b>Serial does not validate solar charging.</b> The firmware measures its own VCC and the LDR only. A0 panel sensing and the charger's CHRG signal are unused, so validate panel voltage, regulated 5 V and charge current with instruments.</div>
<details><summary>Diagnostic firmware settings and programming isolation</summary><p>Build diagnostics with <code>pio run -e pro8_debug</code>; it enables <code>DEBUG_SERIAL=1</code>, keeps real-time <code>TIME_SCALE=1</code>, and reports at 9600 baud. On every reset, a one-time field guide explains the names, units, thresholds, modes, timers and report cadence before live diagnostics begin. Reports are immediate for important changes, every 10 seconds during active confirmation/test/cutoff timing, at 10-percentage-point fade changes, and every 60 seconds when stable. The v0.5 D1 Mini test profile remains awake and publishes those data in Home Assistant; use <code>pio run -e pro8</code> and the low-power D1 profile for final sleep-current testing. This controller has no bootloader: upload only with the separately installed current <code>avrdude</code>, not <code>pio -t upload</code>. Fully disconnect the D1 Mini receiver, battery, panel and LED string before attaching the programmer; reconnect battery power and the receiver only after programming is complete. The exact macOS, Windows, USBasp and Arduino-as-ISP commands are kept in the single <a href="../firmware/lite_controller/PROGRAMMING.md">firmware programming procedure</a>.</p></details>
</section>'''
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>SolarLights | Rebuild and assembly</title>
<style>
:root{--ink:#173047;--muted:#516578;--green:#008572;--amber:#a95e00;--red:#a83232}*{box-sizing:border-box}body{margin:0;background:#f1f5f7;color:var(--ink);font:17px/1.65 system-ui,-apple-system,sans-serif}header,main,footer{max-width:1320px;margin:auto;padding:32px}header{padding-top:52px}h1{font-size:clamp(36px,5vw,62px);line-height:1.1;letter-spacing:-2px;margin:15px 0}h2{font-size:27px;line-height:1.25}h3{font-size:18px}p{max-width:920px;color:var(--muted)}.eyebrow{font-size:13px;letter-spacing:2px;font-weight:800;color:var(--green)}.badge{display:inline-block;background:#fff1d9;color:var(--amber);padding:5px 12px;border-radius:6px;font-size:13px;font-weight:750}nav{display:flex;flex-wrap:wrap;gap:12px;margin-top:24px}a{color:#096b8c;text-underline-offset:4px}nav a,.button{background:white;border:1px solid #cad9e0;border-radius:8px;padding:9px 14px;text-decoration:none}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card,section{background:white;border:1px solid #d9e3e8;border-radius:14px;padding:24px;margin-bottom:24px}.card{margin:0}.card strong{font-size:30px;display:block}.card p{font-size:15px}.hold,.danger,.note{padding:20px 24px;margin:20px 0;border-radius:8px}.hold{background:#fff8e9;border-left:5px solid #c38325}.danger{background:#fff0f0;border-left:5px solid var(--red);color:#702020}.note{background:#eaf7f4;border-left:5px solid var(--green)}.hold p{margin:7px 0}.lede{font-size:18px}.drawing{overflow:auto;border:1px solid #e0e7eb;border-radius:8px;background:white}.drawing svg{width:100%;height:auto;min-width:900px;display:block}.wiring{overflow:auto;background:#10293d;color:#edf7fb;border-radius:8px;padding:20px;font:14px/1.55 ui-monospace,SFMono-Regular,Consolas,monospace}.small{font-size:14px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;vertical-align:top;border-bottom:1px solid #dde5e9;padding:11px}th{background:#edf4f7}.stages{min-width:1050px}.stages td:first-child{white-space:nowrap;background:#f7fafb}code{font-family:ui-monospace,monospace;font-size:13px}details{margin:18px 0}summary{font-weight:700;cursor:pointer}.scroll{overflow:auto}footer{font-size:14px;color:var(--muted)}@media(max-width:760px){header,main,footer{padding:22px}.cards{grid-template-columns:1fr}section{padding:15px}}@media print{body{background:white}nav{display:none}header,main{padding:0}.drawing svg{min-width:0}section{break-before:page;border:0}a{color:inherit}.hold,.danger,.note{border:1px solid}.stages{min-width:0;font-size:10px}.wiring{color:#000;background:#fff;border:1px solid #999}footer{display:none}}
</style><header><div class="eyebrow">PARTS-BIN REBUILD / SEPTEMBER 2026</div><h1>Solar lights, rebuilt<br>for the whole night.</h1><span class="badge">v0.5 · LIVE PROJECT · ACTIVE BENCH DEVELOPMENT</span><p>The current working system: existing panel, TP4056 modules, Pro Mini, light string and D1 Mini telemetry. Continue each measured bench stage in sequence.</p><nav><a href="#s1">Power</a><a href="#s2">Light circuit</a><a href="#s3">D1 Mini profile</a><a href="#s4">D1 test telemetry</a><a href="#s5">Assembly</a><a href="#s6">Current schematic</a><a href="#staging">Staged testing</a><a href="#wires">Wire schedule</a><a href="../../output/pdf/SolarLights_Rev05_Drawings.pdf">Print drawings (A3 PDF)</a></nav></header><main>
<div class="cards"><div class="card"><strong>Reuse</strong><p>1.2 W solar panel, a verified protected TP4056 module, existing cells if suitable, LDR and LED string.</p></div><div class="card"><strong>Convert</strong><p>16 MHz Pro Mini to internal 8 MHz with ISP. Remove regulator and power LED; feed protected battery into VCC.</p></div><div class="card"><strong>Measure</strong><p>LED peak current, charger input and termination, sleep current, radio bursts and daily solar harvest.</p></div></div>
<div class="hold"><b>Before assembly: qualify the unresolved power items.</b><p>U0 is an open item: not fitted, and chosen once the production panel is confirmed (MP1584 is the candidate for the 7.6 V panel). Confirm the TP4056-family module's pad functions, charge-current setting, termination and temperature behaviour. U3 (TPS63802, 3.3 V) is fitted on VBAT_SYS but does not power the D1 on the bench, where the D1 runs on micro-USB; it still needs qualifying as the D1's battery supply. Cell-temperature charging protection remains an outdoor-release requirement.</p><p>The LED string, direct D9 drive and internal-8-MHz fuse conversion are now confirmed project decisions. Ground topology must still be checked on the actual charger; do not bridge battery B- to load OUT-.</p></div>
<section><h2>Your BTE13-010A and available parts</h2><p>The photographed BTE13-010A is the chosen controller and its fuses have been read back as internal 8 MHz, BOD 2.7 V and no bootloader. Q2 is selected as 2N3904. The measured string runs at about 15 mA straight from D9 through R3, with no Q1 fitted.</p><p><a href="BOARD_AND_PARTS.md">Board and inventory assessment</a> · <a href="BTE13-010A-pin-map.svg">Board-specific connection map</a> · <a href="../../output/pdf/BTE13-010A_Pin_Map.pdf">Printable pin map</a></p><p>S9013 is normally NPN; a corrected project inventory copy is provided without modifying your original attachment.</p></section><section><h2>The starting point: dusk to dawn at the measured 15 mA</h2><p>The string was measured on 20-Sep-2026: a 2.56 V drop with no significant dynamic resistance, so the series resistor alone sets the current. With R3 = 47 ohm the branch draws about 21, 15 and 11 mA at 4.20, 3.70 and 3.40 V, and runs straight from D9 with no MOSFET. Commanded duty is now brightness only, so the firmware runs 100% dusk to dawn, halving below 3.45 V and turning off after 30 seconds below 3.30 V. Startup and button tests obey the same cap.</p><p>At 14 dark hours the illustrative whole-system estimate is about <b>238 mAh/day</b> at full brightness, or about <b>133 mAh/day</b> at half. These are scenarios built on one bench measurement and an assumed charge current, not measured performance. Cell capacity, actual shade and usable brightness still decide whether the design meets your needs.</p><p><a href="BUILD_GUIDE.md">Detailed build guide, BOM and bench tests</a> · <a href="VALIDATION.md">Engineering findings and evidence</a></p></section>
'''+''.join(sections)+staging+'''<section id="wires"><h2>Terminal-by-terminal wire schedule</h2><p>Every terminal in a row belongs to the same external net. The charger may join IN- and OUT- internally; this schedule adds no external bridge. Read the actual pad labels and transistor pinout.</p><p><a href="wire-schedule.csv">Download CSV checklist</a> · <a href="reviewed-netlist.json">External wiring model (JSON)</a></p><div class="scroll"><table><thead><tr><th>Net name</th><th>Connect these terminals</th></tr></thead><tbody>'''+rows+'''</tbody></table></div></section>
<section><h2>Validation status</h2><p>Both legacy KiCad sheets export the same 25 nets. Their ERC reports contain 1 error each and 167 / 169 warnings, mostly off-grid drawing endpoints. Matching netlists do not validate the underlying circuit.</p><p>The current scheduler passes nine assertion groups, including dusk debounce, a 14-hour night, the shipped 100% default, low-battery dimming and low-voltage recovery. The BTE13-010A fuse readback confirms internal 8 MHz, BOD 2.7 V and no bootloader; earlier application firmware was written and verified through ISP. v0.5 adds a test-only D1 Mini UART monitor, but it does not create current, energy, panel-voltage or temperature measurements. The staged measurements above remain required to qualify the charger, solar input, physical LED current and complete assembly.</p><p>A future low-cost PCB should first be a module carrier using the exact proven parts. The old KiCad files are retained for audit and must not be sent for fabrication.</p></section>
</main><footer>v0.5 live project guide. Vector schematic source and reproducible generators are included in docs/tools. Original references and baseline firmware are preserved. Engineering sources and current bench status are recorded in VALIDATION.md.</footer></html>'''
# From docs, project output sits two directories up.
page=page.replace('href="../../output/pdf/', 'href="../../output/pdf/')
(DOC/'ASSEMBLY.html').write_text(page)
print('Generated guide and validated external wire schedule')
